### ISSUE TITLE
lpdf:FPT - the compiler is unable to type-check this expression in reasonable time

### ISSUE THREAD

**Issue by dpott197** [strike65/SwiftyStats#2]
Pods/_Prebuild/SwiftyStats/SwiftyStats/CommonSource/ProbDist/ProbDist-StudentT.swift:83:102: the compiler is unable to type-check this expression in reasonable time; try breaking up the expression into distinct sub-expressions

    let lpdf:FPT = lgamma1( half * ( df + 1 ) ) - half * log1( df * FPT.pi ) - lgamma1( half * df )  - expr
                   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~

**Comment by strike65** [comment]
Yes. This problem is well known. The Swift-Type-Checker cannot handle long expressions with generic parameters.
I am in the process of fixing this problem.
See also here:[no-longer-able-to-type-check-expressions-with-xcode]( https://forums.swift.org/t/no-longer-able-to-type-check-expressions-with-xcode-10-2-caused-by-new-simd-api/22873)

**Comment by strike65** [comment]
Fixed in current master
